### ISSUE TITLE
Timeout setting don't work

### ISSUE THREAD

**Issue by neyp** [algolia/algoliasearch-client-ruby#314] opened 2018-09-21 19:57 UTC
- Algolia Client Version: 1.23.2
- Language Version: 5.1.6

### Description
Timeout settings don't work. The gem doesn't throw a timeout exception.

### Steps To Reproduce
Configure your client with:
```
batch_timeout: 120,
connect_timeout: 2,
receive_timeout: 10,
search_timeout: 5,
send_timeout: 10
```

**Comment by raphi** [comment] 2018-09-24 09:30
Hi @neyp on which timeout exactly are you experiencing the issue? The `batch_timeout`, `connect_timeout`... ?

**Comment by mathdecastilho** [comment] 2018-09-24 15:56
In this case we are using `index.search`, it probably uses `search_timeout`.

**Comment by raphi** [comment] 2018-09-25 11:34
cc @julienbourdeau

**Comment by julienbourdeau** [comment] 2018-10-01 08:56
Hi, 

Our lib relies on the [HttpClient](https://rubygems.org/gems/httpclient/) gem and timeout seems to  be set correctly.

Could you share more code, like how you create the client see if it could explain what is happening?

**Comment by julienbourdeau** [comment] 2018-12-17 16:52
@neyp @mathdecastilho If the issue isn't fixed, would you mind sharing some code to demonstrate what's happening and what you expect?

**Comment by mathdecastilho** [comment] 2018-12-17 18:17
hello @julienbourdeau, I'm sorry.
Apparently it's ok, you can close this issue.

**Closed** 2018-12-18 14:52 UTC
